apiVersion: v1
kind: Pod
metadata:
 name: attachedpvcpod
 labels:
  env: testing
  region: IN
spec:
 containers:
  - name: pvcattachedcontainer
    image: httpd
    volumeMounts:
     - name: web-vol
       mountPath: /var/www/html
 volumes:
  - name: web-vol
    persistentVolumeClaim:
     claimName: web-pvc 