apiVersion: v1
kind: ReplicationController
metadata:
 name: web-rc
spec:
 replicas: 3
 selector:
  app: web-rc
 template:
  metadata:
   name: web-pod
   labels:
    app: web-rc
  spec:
   containers:
    - name: rc-web-containers
      image: httpd
      ports:
       - containerPort: 80