apiVersion: v1
kind: Pod
metadata:
 name: wppod
 labels:
  env: testing
  region: IN
spec:
 containers:
  - name: wpcontainer
    image: wordpress:5.1.1-php7.3-apache
    env:
     - name: WORDPRESS_DB_HOST
       value: 172.17.0.6
     - name: WORDPRESS_DB_PASSWORD
       valueFrom:
        secretKeyRef:
          name: mysqlpass
          key: password
     - name: WORDPRESS_DB_NAME
       value: pvcdb
     - name: WORDPRESS_DB_USER
       valueFrom:
        secretKeyRef:
         name: mysqlpass
         key: username
    ports:
     - containerPort: 80
    volumeMounts:
     - name: wpvol
       mountPath: /var/www/html
 volumes:
  - name: wpvol
    persistentVolumeClaim:
     claimName: wppvc 