apiVersion: v1
kind: Service
metadata:
 name: my-service
 labels:
  apps: my-app-service
spec:
 selector:
  env: testing
 type: NodePort
 ports:
  - nodePort: 30000
    port: 81
    targetPort: 80 

